mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


#app_name = 'poll'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('poll.urls')),
]

poll/urls.py
from django.conf.urls import url
from poll import views

app_name ='poll'
urlpatterns = [
    url(r"^$", views.QuestionTypeView.as_view(), name="main_page"),
    url(r"^questions/(?P<pk>\d+)/$", views.QuestionBriefView.as_view(), name="question_list"),
    url(r"^option/(?P<pk>\d+)/$", views.QuestionDetailView.as_view(), name="question_detail"),
    url(r"^type/$", views.TypeCreateView.as_view(), name="create_type"),
    url(r"^createquestion/(?P<pk>\d+)/$", views.QuestionCreateView.as_view(), name="create_question"),
    url(r"^createoption/(?P<pk>\d+)/$", views.OptionCreateView.as_view(), name="create_option"),
    url(r"^updatequestion/(?P<pk>\d+)/$", views.QuestionUpdateView.as_view(), name="update_question"),
    url(r"^deletequestion/(?P<pk>\d+)/$", views.QuestionDeleteView.as_view(), name="delete_question"),
    url(r"^updateoption/(?P<pk>\d+)/$", views.OptionUpdateView.as_view(), name="update_option"),
    url(r"^result/(?P<pk>\d+)$", views.ResultDisplayView.as_view(), name="display_result"),
    url(r"^deletechoice/(?P<pk>\d+)$", views.OptionDeleteView.as_view(), name="delete_option"),
    url(r"^deletetype/(?P<pk>\d+)$", views.TypeDeleteView.as_view(), name="delete_type"),
    url(r"^contact/$",views.ContactAddView.as_view(), name="contact_views")







]

poll/models.py
from django.db import models
import datetime
import django
from django.utils import timezone
# Create your models here.


class QuestionType(models.Model):

	# this is model for question type 
	topic = models.CharField(max_length=200)

	def __str__(self):

		return self.topic

class Question(models.Model):

	question_type = models.ForeignKey(QuestionType)
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField(default= django.utils.timezone.now)
	hit_ques = models.IntegerField(default =0)

	# def was_published_recently(self):
	# 	now = timezone.now()
	# 	return now - datetime.timedelta(days=1) <= self.pub_date <= now

	# 	#return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	def __str__(self):

		return self.question_text


class Choice(models.Model):

	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	deleted = models.BooleanField(default=False)
	
	#def soft_del(self):
    #    self.deleted = True            
     #   self.save()

	
	def __str__(self):

		return self.choice_text

class Contact(models.Model):
	name = models.CharField(blank =True, max_length=100, help_text="enter name")
	address = models.CharField(blank =True, max_length=200, help_text="enter name")

	def __str__(self):
		return self.name

poll/forms.py
from django import forms
from poll.models import Question, QuestionType, Choice,Contact


class QuestionTypeForm(forms.ModelForm):

    class Meta:
        model = QuestionType
        fields = '__all__'


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        exclude =['hit_ques']
        fields = '__all__'
        
        
class ChoiceForm(forms.ModelForm):
    # error_messages = {
    #         'required': 'my custom error message',
    #     }
    class Meta:
        

        model = Choice
        exclude =['votes']
        fields = '__all__'
        # widgets = {'choice_text': forms.RadioSelect()}

        
class ContactForm(forms.ModelForm):
   

       # name = forms.CharField(help_text="nameplzz")
    class Meta:
        model = Contact
        fields = '__all__'

poll/views.py
from django.shortcuts import render,HttpResponse
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from poll.models import QuestionType, Question, Choice, Contact
from django.core.urlresolvers import reverse_lazy
from poll.forms import QuestionTypeForm, QuestionForm, ChoiceForm, ContactForm
from django.shortcuts import get_object_or_404, render
from django.db.models import Max, Sum
# Create your views here.


class QuestionTypeView(ListView):

    # lists all question type
    model = QuestionType
    template_name = "poll/main_page.html"
    context_object_name ="type_list"

    
    def get_popular(self):

        political = QuestionType.objects.get(topic = "Political")
        maxx = Question.objects.all().exclude(question_type=political).aggregate(Max('hit_ques'))
        return Question.objects.get(hit_ques = int(maxx['hit_ques__max']))

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['popular'] = self.get_popular()
        return context   


        
class QuestionBriefView(ListView):

    model = Question
    template_name = "poll/question_list.html"


    def get_queryset(self,**kwargs):
        topic_name = get_object_or_404(QuestionType, id=self.kwargs['pk'])
        return Question.objects.filter(question_type=topic_name)
    
    def get_data(self):
        topic_name = get_object_or_404(QuestionType, id=self.kwargs['pk'])
        ques = Question.objects.filter(question_type__topic=topic_name).count()
        return ques
        

    def get_context_data(self, **kwargs):
       
        context = super(QuestionBriefView, self).get_context_data(**kwargs)
        context['typeid']=self.kwargs['pk']
        context['show']=self.get_data()
        return context



class QuestionDetailView(DetailView):

    model = Question
    template_name = "poll/question_detail.html"


    def get_total (self):

        query = self.object.choice_set.all()        
        total = query.aggregate(Sum('votes'))
        return total['votes__sum']

    def get_data(self, **kwargs):
        ques_id = self.kwargs['pk']
        page =  Question.objects.get(id =ques_id)
        page.hit_ques = page.hit_ques + 1
        page.save()

        return page.hit_ques

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        context['view']= self.get_data()
        context['total']=self.get_total()
        return context
   
    

class TypeCreateView(CreateView):


    form_class = QuestionTypeForm
    template_name = "poll/create_type.html"
    success_url = reverse_lazy('poll:main_page')



class QuestionCreateView(CreateView):


    form_class = QuestionForm
    template_name = "poll/create_question.html"

    def get_initial(self):

        initials = super(QuestionCreateView, self).get_initial()
        initials['question_type'] = self.kwargs['pk']
        return initials

    def get_success_url(self,**kwargs):
        
        post = self.object.question_type # it prints out the clicked question type or the new created question
        #print(self.object.id) # printts the id of question
        return reverse_lazy('poll:question_list', args = (post.id,))

        

class OptionCreateView(CreateView):


    form_class = ChoiceForm
    template_name = "poll/create_option.html"

    def get_initial(self):
        initials = super(OptionCreateView, self).get_initial()
        initials['question'] = self.kwargs['pk']
        return initials

    def get_success_url(self,**kwargs):

        post = self.object.question 
        return reverse_lazy('poll:question_detail', args = (post.id,))
    
    
    
class QuestionUpdateView(UpdateView):

    model = Question
    template_name = "poll/create_question.html"
    form_class = QuestionForm

    def get_success_url(self,**kwargs):

        post = self.object.question_type # it prints out the clicked question type or the new created question
        #print(self.object.id) # printts the id of question
        return reverse_lazy('poll:question_list', args = (post.id,))



class QuestionDeleteView(DeleteView):

    model = Question
    template_name = "poll/delete_question.html"


    def get_success_url(self,**kwargs):

        post = self.object.question_type # it prints out the clicked question type or the new created question
        #self.soft_delete()
        return reverse_lazy('poll:question_list', args = (post.id,))



class OptionDeleteView(DeleteView):

    model = Choice
    template_name = "poll/delete_option.html"
    #alive = True

    #def __init__(self,**kwargs):
    # Bulk delete bypasses individual objects' delete methods.
       # Choice.objects.get(id =self.kwargs['pk']).delete(alive=False)
     #   print(self.object.question)

    def get_success_url(self,**kwargs):
        post = self.object.question
        print(post)
        pp=(self.object.id)
        Choice.objects.get(id =pp).delete(alive=False)
        return reverse_lazy('poll:question_detail', args = (post.id,))




class OptionUpdateView(UpdateView):

    model = Choice
    template_name = "poll/create_option.html"
    form_class = ChoiceForm

    def get_success_url(self,**kwargs):

        post = self.object.question 
        return reverse_lazy('poll:question_detail', args = (post.id,))



class ResultDisplayView(DetailView):            # to display the final results

    template_name = 'poll/display_result.html'
    model = Choice

    def get_data (self, **kwargs):
        
        ques_id = self.kwargs['pk']
        question = get_object_or_404(Question, id=ques_id)
        return question

    def get_context_data(self, **kwargs):
            print(self.object)
            context = super(ResultDisplayView, self).get_context_data(**kwargs)
            question = self.get_data() 
            context['page']=question

            try:
                selected_choice = question.choice_set.get(id=self.request.GET["choice"])
                selected_choice.votes += 1
                selected_choice.save()
                                  
            except Exception as ex :
                context['message']="not selected "+str(ex)
                
            return context



class TypeDeleteView(DeleteView):

    model = QuestionType
    template_name = "poll/delete_type.html"

    def get_success_url(self,**kwargs):
        
        post = self.object.topic
        return reverse_lazy('poll:main_page')



class ContactAddView(CreateView):

    
    model = Contact
    template_name = "poll/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy('poll:contact_views')

    def form_valid(self, form):
        self.request.session['name'] = form.cleaned_data
        self.request.session['address'] = form.cleaned_data
        return super(ContactAddView, self).form_valid(form)

class ResultView(TemplateView):
    template_name = "contact.html"
    
    
    
    
# from django.http import HttpResponseRedirect
# from django.shortcuts import render, get_object_or_404

# # Create your views here.
# from django.urls import reverse
# from django.utils.datastructures import MultiValueDictKeyError
# from django.views.generic import TemplateView, ListView, DetailView

# from main.models import Question, Choice


# class HomePageView(TemplateView):
#     template_name = 'main/homepage.html'


# class ListPageView(ListView):
#     model = Question
#     template_name = 'main/list_questions.html'


# class DetailPageView(DetailView):
#     model = Question
#     template_name = 'main/detail_questions.html'


# class ResultPageView(DetailView):
#     model = Question
#     template_name = 'main/result.html'

#     # always call POST method if the action is post or GET if the method is GET

#     # def pos(self, request, *args, **kwargs):
#     #     print(self.kwargs)

#     # def get_context_data(self, **kwargs):
#     #     context = super().get_context_data(**kwargs)
#     #     selected_choice = self.request.GET['radio_choice']
#     #     choice_number = get_object_or_404(Choice, pk=selected_choice)
#     #     choice_number.vote += 1
#     #     choice_number.save()
#     #     return context

#     def dispatch(self, request, *args, **kwargs):
#         # print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
#         obj = self.get_object()
#         # print('#########################')
#         try:
#             # choice_selected = obj.choices.get(pk=self.request.GET['radio_choice'])
#             choice_selected = get_object_or_404(Choice, pk=self.request.GET['radio_choice'])
#             # print('-------------------')
#         except KeyError:
#             #print('cool', obj.pk)
#             return HttpResponseRedirect(reverse('main:detail_questions', args=[obj.pk, ]))
#         except AttributeError:
#             return HttpResponseRedirect(reverse('main:detail_questions', args=[obj.pk, ]))
#         else:
#             print(choice_selected)
#             choice_selected.vote += 1
#             choice_selected.save()
#             return super().dispatch(request, *args, **kwargs)


# # #
# # def homepage(request):
# #     context = {'name': 'dikshant', 'age': 25}
# #     return render(request, 'main/homepage.html', context)
# #
# #
# # def list_questions(request):
# #     context = {'context': Question.objects.all()}
# #     return render(request, 'main/list_questions.html', context)
# #
# #
# # def detail_questions(request, question_pk):
# #     context = {'context': get_object_or_404(Question, pk=question_pk), }
# #     return render(request, 'main/detail_questions.html', context)
# #
# #
# # def vote_choice(request, question_pk):
# #     context = {'context': get_object_or_404(Question, pk=question_pk), }
# #     try:
# #         obj = get_object_or_404(Choice, pk=request.POST['radio_choice'])

poll/templates/poll/contact.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<html>
 <h3>Contact Fomr:</h3>
<form action=''  method='POST'>
{% csrf_token %}
{% for field in form %}
  <div>
     
  <label>{{ field.label_tag }}</label>
  </div>
  <div>
      {{ field }}

  </div>

{% endfor %}


    <div>
      <button type="submit">Save</button>
    </div>
  </div>
</form>
</html>

Last Contact submitted by user details:<br>

{{ request.session.name}}

poll/templates/poll/create_option.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<html>
 <h3>Add New Option To this Question:</h3>
<form action=''  method='POST'>
{% csrf_token %}
{% for field in form %}
  <div>
      <span>{{ field.errors }}</span>
 
  <label>{{ field.label_tag }}</label>
  </div>
  <div>
      {{ field }}

  </div>

{% endfor %}


    <div>
      <button type="submit">Save</button>
    </div>
  </div>
</form>
</html>

poll/templates/poll/create_question.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<html>
 <h3>Create A New QUestion Type:</h3>
<form action=''  method='POST'>
{% csrf_token %}
{% for field in form %}
  <div>
     
  <label>{{ field.label_tag }}</label>
  </div>
  <div>
      {{ field }}

  </div>

{% endfor %}


    <div>
      <button type="submit">Save</button>
    </div>
  </div>
</form>
</html>

poll/templates/poll/create_type.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<html>
 <h3>Create A New QUestion Type:</h3>
<form action=''  method='POST'>
{% csrf_token %}
{% for field in form %}
  <div>
      <span>{{ field.errors }}</span>
 
  <label>{{ field.label_tag }}</label>
  </div>
  <div>
      {{ field }}

  </div>

{% endfor %}


    <div>
      <button type="submit">Save</button>
    </div>
  </div>
</form>
</html>

poll/templates/poll/delete_option.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

poll/templates/poll/delete_question.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

poll/templates/poll/delete_type.html
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

poll/templates/poll/display_result.html
<center><a href ="{% url 'poll:question_detail' page.id %}">Vote Again!!</a></center>


{% if message == None %}

<br>
<!--Thank you for the votes . Now you will be auto redirected to main page
<meta http-equiv="refresh" content="8;url=http://localhost:8000" >
<br> -->
<table border = "5">
<strong>{{page}}</strong>
<th> Options </th>
<th>Votes</th>

{% for choice in page.choice_set.all %}
<tr>
  

       <td width = "200"> {{choice.choice_text}}</td>
       <td>{{choice.votes}}</td>

</tr>
    
{% endfor %}

</table>
{% endif %}



{{message}}

poll/templates/poll/main_page.html
<html>
<a href ="{% url 'poll:create_type' %}">Create A New Category</a>

<center><strong>POLL APP</strong><br>


<table  border="5">
<th><center>QUESTION TOPICS : {{type_list|length}}</center></th>
{% for type in type_list %}
	<tr>

	<td><a href = "{% url 'poll:question_list' type.id  %}">{{type.topic}}</a>
	<a href = "{% url 'poll:delete_type' type.id %}">
		<button type="button">Delete </button></a>


	</td>

	</tr>
{%  endfor %}


</table>
</center>
<html>


<br>

<table border ='4'>


<th>Most Popular QUESTION</th>

<tr>
<td>

<a href = "{% url 'poll:question_detail' popular.id  %}">{{popular}}</a>
</td>
</tr>
</table>
Political Type Question Excluded

<a href = "{% url 'poll:contact_views' %}">click here to fill contact</a>

poll/templates/poll/question_detail.html
<center>
<center><a href ="{% url 'poll:main_page' %}">Home</a></center>

<table  border="5">
<th><center>QUESTION </center></th>
<th><center>OPTIONS : {{object.choice_set.all|length}} </center></th>
<form action="{% url 'poll:display_result'  object.id%}" method="GET">
{% csrf_token %}

	<tr>

	<td>{{object}}</td>
	<td>{% for choice in object.choice_set.all %}
    	

	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} <a href = "{% url 'poll:update_option' choice.id %}">
	<button type="button">Update </button></a>

	<a href = "{% url 'poll:delete_option' choice.id %}">
	<button type="button">Delete </button></a>

	  </label><br>
    

		{% endfor %}</td>


	</tr>

<input type="submit" value="Vote" />
</form>

</table>
<br>
Total votes for this question till now : {{total}}
<br>
<center><a href = "{% url 'poll:create_option' object.id %}">Add new option for this question</a></center>



</center>
number of times this question viewed : {{view}}
<br>

poll/templates/poll/question_list.html
<center>
<center><a href ="{% url  'poll:main_page' %}">Home</a></center>


<table  border="5">

<th>{{object}}  Questions : {{show}}</th> 
{% for query in object_list %}
	
  	<tr>

 	 	<td>

 		<a href = "{% url 'poll:question_detail' query.id  %}">{{query.question_text}}</a><a href = "{% url 'poll:update_question' query.id %}">
		<button type="button">Update </button></a>
		<a href = "{% url 'poll:delete_question' query.id %}">
		<button type="button">Delete </button></a>

		</td>
   
 	</tr>
	

{% endfor %}
</table>

<center><li><a href = "{% url 'poll:create_question' typeid %}">CREATE A NEW Question In this Category</a></center>


</center>